# Generated by Django 5.1.4 on 2024-12-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='resturant_images/')),
                ('food', models.ManyToManyField(related_name='resturants', to='main.food')),
            ],
        ),
    ]
