# Generated by Django 5.1.4 on 2025-01-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
