# Generated by Django 5.1.4 on 2025-01-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_discountcode_food_selled_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default='food_images/default.jpg', null=True, upload_to='food_images/'),
        ),
    ]
